### ISSUE TITLE
Design Criteria, Sample Calculations and Simulations

### ISSUE THREAD

**Issue by Thesoap** [CPHB-KEPP/KP-UFO#5]
6/10
I feel like the more tests, samples and other ways to give information about the problem could be made. The "What we did" feels short and could use some more information about how the fix is working.

**Comment by Skiparin** [comment]
To be specific, I find the ssh connection process to be a bit mysterious, where do we run the commands, what is openssl, what do the commands do, what is deplay-key.enc and why don't we need it anymore, what is deploy-key, do we make it our private key?

**Comment by philliphb** [comment]
We have explained more about how we establish a connection to the server and added more details about the .travis.yml file.
